config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'static_pages#home'

  get 'about_team' => 'static_pages#about'
  get 'about' => 'static_pages#about_blog'
  get 'admin' => 'static_pages#admin'
  get 'contact' => 'static_pages#contact'
  get 'posts_admin' => 'posts#index_admin'

  resources :posts
  resources :clubs
  resources :team_selections
  resources :contacts, only: [:create, :new]

  get '*path' => redirect('/')

end

app/models/club.rb
class Club < ActiveRecord::Base
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name, :validate => true
	attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message, :validate => true
	attribute :nickname, :captcha => true

	def headers 
		{
			:subject => 'Contact form',
			:to => "naterek@gmail.com",
			:from => %("#{name}" <#{email}>)
		}
	end	
end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
  friendly_id :title, use: :slugged

	default_scope -> { order(created_at: :desc) }
	validates :title, presence: true, length: { maximum: 60 }
	validates :content, presence: true
end

app/models/settings.rb
# RailsSettings Model
class Settings < RailsSettings::CachedSettings
	
end

app/models/team_selection.rb
class TeamSelection < ActiveRecord::Base
  belongs_to :club
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
	before_action :authenticate_user!
	before_action :find_club, only: [:show, :edit, :update, :destroy]
	layout 'admin'

	def index
		@clubs = Club.all
	end

	def new
		@club = Club.new
	end

	def create
		@club = Club.new club_params

		if @club.save
			redirect_to clubs_path, notice: "Bravo Rafal. That club was successfully saved!"
		else
			render 'new', notice: "I was unable to save it."
		end
	end

	def show
	end

	def edit
		
	end

	def update
		if @club.update club_params
			redirect_to clubs_path, notice: "Club was successfully saved!"
		else
			render 'edit'
		end
	end

	def destroy
		@club.destroy
		redirect_to clubs_path
	end

	private

	def club_params
		params.require(:club).permit(:name, :abbrev)
	end

	def find_club
		@club = Club.find(params[:id])
	end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      #flash.now[:notice] = 'Dziękuję za wiadomość.'
    else
      flash.now[:error] = 'Wystapił problem z wysłaniem wiadomości.'
      render :new
    end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	layout 'admin', only: [:new, :edit, :index_admin]

	def index
		@posts = Post.paginate(:page => params[:page], :per_page => 6)
	end

	def index_admin
		@posts = Post.paginate(:page => params[:page], :per_page => 20)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "Bravo Rafal. Your post was successfully saved!"
		else
			render 'new', notice: "I was unable to save it."
		end
	end

	def show
	end

	def edit
		
	end

	def update
		if @post.update post_params
			redirect_to @post, notice: "Your post was successfully saved!"
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_admin_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :content, :slug)
	end

	def find_post
		@post = Post.friendly.find(params[:id])
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:admin]
  layout 'admin', only: [:admin]

  def home
    @team_selections = TeamSelection.all
  	@posts = Post.take(3)
  end

  def about
    @post = Post.find_by slug: 'historia-kasztaniakow'
  end

  def about_blog
    
  end

  def admin
  	
  end
end

app/controllers/team_selections_controller.rb
class TeamSelectionsController < ApplicationController
	before_action :authenticate_user!
	before_action :find_team_selection, only: [:show, :edit, :update, :destroy]
	layout 'admin'

	def index
		@team_selections = TeamSelection.all
	end

	def new
		@team_selection = TeamSelection.new
	end

	def create
		@team_selection = TeamSelection.new team_selection_params

		if @team_selection.save
			redirect_to team_selections_path, notice: "Bravo Rafal. That team selection was successfully saved!"
		else
			render 'new', notice: "I was unable to save it."
		end
	end

	def show
	end

	def edit
		
	end

	def update
		if @team_selection.update team_selection_params
			redirect_to team_selections_path, notice: "Team selection was successfully saved!"
		else
			render 'edit'
		end
	end

	def destroy
		@team_selection.destroy
		redirect_to team_selections_path
	end

	private

	def team_selection_params
		params.require(:team_selection).permit(:name, :position, :club_id)
	end

	def find_team_selection
		@team_selection = TeamSelection.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def set_team_line(players)
		line = ""
		i = 0
		case players.count
		when 2
			players.each do |player|
				line += "<td></td>"
				line += "<td>#{image_tag(player.club.abbrev+'.png')}<span>#{player.name}</span></td>"
			end
			line += "<td></td>"
		when 3
			if players.first.position == "3"
				players.each do |player|
					if (i == 1 || i == 2)
						line += "<td></td>"
					end
					line += "<td>#{image_tag(player.club.abbrev+'.png')}<span>#{player.name}</span></td>"
					i+=1
				end
			else
				players.each do |player|
					if i == 0
						line += "<td></td>"
					end
					line += "<td>#{image_tag(player.club.abbrev+'.png')} <span>#{player.name}</span></td>"
					i+=1
				end
				line += "<td></td>"
			end
		when 4
			players.each do |player|
				if i == 2
					line += "<td></td>"
				end
				line += "<td>#{image_tag(player.club.abbrev+'.png')}<span>#{player.name}</span></td>"
				i+=1
			end
		when 5
			players.each do |player|
				line += "<td>#{image_tag(player.club.abbrev+'.png')}<span>#{player.name}</span></td>"
			end
		end		
		line.html_safe
	end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_selections_helper.rb
module TeamSelectionsHelper
end

app/views/clubs/_form.html.erb
<%= form_for @club do |f| %>
	<% if @club.errors.any? %>
		<h2><%= pluralize(@club.errors.count, "error") %> prevented this club from saving:</h2>
		<ul>
			<% @club.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>

		<% end %>
		<div class="form-group">
			
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
		</div>

		
		<div class="form-group">
			<%= f.label :abbrev %>
			<%= f.text_field :abbrev, class: 'form-control' %>
	
		</div>
		

		<%= f.submit 'Submit', class: "btn btn-default" %>
<% end %>

app/views/clubs/edit.html.erb
<h1 class="sub-header">Edit club</h1>

<%= render 'form' %>

app/views/clubs/index.html.erb
<h1 class="sub-header">Clubs</h1>
<table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Abbrev</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @clubs.each do |club| %>
        <tr>
          <td><%= club.id %></td>
          <td><%= club.name %></td>
          <td><%= club.abbrev %></td>
          <td>
            <%= link_to edit_club_path(club) do %>
              <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            <% end %>
          </td>
          <td>
            <%= link_to club_path(club), method: 'delete', data: {confirm: 'Are you sure?'} do %>
              <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/clubs/new.html.erb
<h1 class="sub-header">New club</h1>

<%= render 'form' %>

app/views/contacts/_error_messages.html.erb
<% if @contact.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Formularz zawiera <%= I18n.t :error, count: @contact.errors.count %>.
    </div>
    <ul>
    <% @contact.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/contacts/create.html.erb
<div class="container message">
  <div class="row text-center">
    <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
      <hr class="black wider">
     <br>
      <h2>Dziękuję za wiadomość!</h2>
      <p>Odpiszę w najbliższej wolnej chwili.</p>
      <br>
      <hr class="black wider">

    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container message">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
      <h2 class="text-center">Napisz do mnie!</h2>
      <hr class="black">

      <%= form_for @contact do |f| %>
        <%= render 'error_messages' %>
        <div class="field form-group">
          <%= f.label :name, "Imię" %>
          <%= f.text_field :name, required: false, class: 'form-control' %>
        </div>

        <div class="field form-group">
          <%= f.label :email %>
          <%= f.text_field :email, required: false, class: 'form-control', novalidate: :novalidate %>
        </div>

        <div class="field form-group">
          <%= f.label :message, "Wiadomość" %>
          <%= f.text_area :message, as: :text, class: 'form-control' %>
        </div>

        <div class="hidden">
          <%= f.label :nickname %>
          <%= f.text_field :nickname, hint: 'Leave this field blank' %>
        </div>

        <%= f.submit "Wyślij wiadomość", class: 'btn-custom' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 col-xs-10 col-xs-offset-1 copyright-div">
                <p class="copyright text-muted">Copyright &copy; Kasztaniaki 2016</p>
            </div>
             <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 col-xs-10 col-xs-offset-1 media-footer-div">
                <ul class="list-inline text-center">
                    <li>
                        <%= link_to "https://github.com/natra/kasztaniaki-blog" do %>
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        <% end %>
                    </li>
                </ul>
        </div>
            
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Kasztaniaki", root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse main-nav" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to "Home", root_path %>
                </li>
                <li>
                    <%= link_to "Posty", posts_path %>
                </li>
                <li>
                    <%= link_to "O blogu", about_path %>
                </li>
                <li>
                    <%= link_to "O drużynie", about_team_path %>
                </li>
                <li>
                    <%= link_to "Kontakt", new_contact_path %>
                </li>
                <% if user_signed_in? %>
                    <li>
                        <%= link_to "Admin", admin_path %>
                    </li>
                    <li>
                        <%= link_to "Wyloguj", destroy_user_session_path, method: :delete %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>
<header class="brand-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Kasztaniaki</h1>
                    <hr class="white">
                    <span class="subheading">Blog o pewnej drużynie FPL</span>
                </div>
            </div>
        </div>
    </div>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Kasztaniaki | Admin panel</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <%= stylesheet_link_tag 'dashboard' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          
          <%= link_to "Kasztaniaki", root_path, class: "navbar-brand" %>
        </div>

    
    </div>
    </nav>
    <div class="container-fluid">
      <div class="row">
         <div class="col-sm-3 col-md-2 col-xs-12 sidebar">
          
          <%= link_to admin_path, class: 'btn btn-default' do %>
            <span class="glyphicon glyphicon-dashboard" aria-hidden="true"></span> Dashboard
          <% end %>
            
          <h3><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Posts</h3>
            
          <%= link_to "Show all posts", posts_admin_path, class: 'btn btn-default' %>
          <%= link_to "Add post", new_post_path, class: 'btn btn-default' %>
           
            <h3>
              <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Team selections  
            </h3>
            
            <%= link_to "Show team selections", team_selections_path, class: 'btn btn-default' %>
            <%= link_to "Add team selection", new_team_selection_path, class: 'btn btn-default' %>
                
            <h3>
              <i class="fa fa-futbol-o"></i> Clubs
            </h3>
          
            <%= link_to "Show clubs", clubs_path, class: 'btn btn-default' %>
            <%= link_to "Add club", new_club_path, class: 'btn btn-default' %>
                
          </div>




    
          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 col-xs-12 main">
            <% if notice %>
              <hr class="black">
              <p class="notice"><%= notice %></p>
              <hr class="black">
              <br>
            <% elsif alert %>
              <hr class="black">
              <p class="alert"><%= alert %></p>
              <hr class="black">
              <br>
            <% end %>
            <%= yield %>
          </div>

      </div>
    </div>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Kasztaniaki</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin-ext' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<%= render 'layouts/header' %>
<% if notice %>
	<hr class="black">
	<p class="notice"><%= notice %></p>
	<hr class="black">
	<br>
<% elsif alert %>
	<hr class="black">
	<p class="alert"><%= alert %></p>
	<hr class="black">
	<br>
<% end %>


<%= yield %>

<%= render 'layouts/footer' %>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread" class="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    
    var disqus_config = function () {
        this.page.url = '<%= url_for([@post, {only_path: false}]) %>';  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        this.page.title = '<%= @post.title %>';
    };
    
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        
        s.src = '//kasztaniaki.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>

		<% end %>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control' %>
		</div>
		

		<div class="form-group">
			<%= f.label :content, "Write your post here" %>
			<%= f.text_area :content, class: 'form-control' %>
		</div>

		


		<%= f.submit 'Submit', class: 'btn btn-default' %>
<% end %>

app/views/posts/_show.html.erb
<div class="container article">
	<div class="row">
		<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
			<div class="post">
				<h1><%= @post.title %></h1>
        <hr class="black" />
				<%== @post.content %>
        <div class="pub-date">
          <%= I18n.l @post.created_at, :format => :post %>
        </div>
        <% if user_signed_in? %>
          <%= link_to "Edit", edit_post_path(@post), class: 'btn-custom' %>
          <%= link_to "Delete", post_path(@post), method: :delete, class: 'btn-custom', data: {confirm: 'Are you sure?'} %>
        <% end %>
			</div>
			<hr class="black">
			<%= render 'posts/disqus' %>
		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<h1 class="sub-header">Edit post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-5 col-lg-offset-1 col-md-10 col-md-offset-1">
            <% @posts.each_with_index do |post, index| %>
							<div class="post-preview">
	            	<%= link_to (post) do %>
	                <h2 class="post-title">
	                 	<%= post.title %>
	                </h2>
	              <% end %>
              	<p class="post-meta">Opublikował <%= link_to "Rafał Nater", new_contact_path %> dnia <%= I18n.l post.created_at, :format => :home %></p>
            	</div>
            	<hr>
              <% if index == 2 %>
                </div>
                <div class="col-lg-5 col-lg-offset-0 col-md-10 col-md-offset-1">
              <% end %>
            <% end %>
        </div>
    </div>
    <div class="pagination-main">
      <%= will_paginate @posts %>
    </div>
               
</div>

app/views/posts/index_admin.html.erb
<h1 class="sub-header">Posts</h1>
<table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.id %></td>
          <td><%= link_to post.title, post %></td>
          <td>
            <%= link_to edit_post_path(post) do %>
              <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            <% end %>
          </td>
          <td>
          <%= link_to post_path(post), method: :delete, data: { confirm: 'Are you sure?'} do %>
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/posts/new.html.erb
<h1 class="sub-header">New post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= render 'posts/show' %>

app/views/static_pages/_team.html.erb
<table class="gw-team-table">
      <tr>
          
          <% if @team_selections.where(position: 0).length != 0 %>
            <td></td><td></td><td><img alt="Shirt2" src='<%= asset_path 'gk.png' %>' /> <span>
             <%= @team_selections.where(position: 0).first.name %></span></td><td colspan="2" class="gw-num"><span><%= Settings.gw %></td>
          <% end %>

         
      </tr>
      <tr>
          <%= set_team_line(@team_selections.where(position: 1)) %>
      </tr>
      <tr>
          <%= set_team_line(@team_selections.where(position: 2)) %>

      </tr>
      <tr>
          <%= set_team_line(@team_selections.where(position: 3)) %>

      </tr>
      <tr><td></td></tr>
</table>
<table class="res-table">
    <tr>
      <% @team_selections.where(position: '4').each do |reserve| %>
        <td><span><%= reserve.name %></span></td>
      <% end %>
    </tr>
</table>

app/views/static_pages/admin.html.erb
<h1 class="sub-header">Dashboard</h1>

app/views/static_pages/home.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-8 col-sm-offset-2">

            <% @posts.each do |post| %>

            <div class="post-preview">
                 <%= link_to(post) do %>
                    <h2 class="post-title">
                        <%= post.title %>
                    </h2>
                 <% end %>
                <p class="post-meta">Opublikował <%= link_to "Rafał Nater", new_contact_path %> dnia <%= I18n.l post.created_at, :format => :home %></p>
            </div>
            <hr>

            <% end %>
            <!-- Pager -->
            <ul class="pager">
                <li class="next">
                    <%= link_to posts_path do %>
                        Starsze posty &rarr;
                    <% end %>
                </li>
            </ul>
            <hr class="hr-home">
        </div>
        
        <div class="col-lg-6 col-lg-offset-0 text-center team-container col-md-6 col-md-offset-0 col-sm-8 col-sm-offset-2">
            <%= render "team" %>
        </div>
    </div>
</div>

app/views/team_selections/edit.html.erb
<h1 class="sub-header">Edit team selection</h1>

<%= render 'form' %>

app/views/team_selections/index.html.erb
<h1 class="sub-header">Team Selections</h1>
<table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Position</th>
        <th>Club</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @team_selections.each do |team_selection| %>
        <tr>
          <td><%= team_selection.id %></td>
          <td><%= team_selection.name %></td>
          <td><%= team_selection.position %></td>
          <td><%= team_selection.club_id %></td>
          <td>
            <%= link_to edit_team_selection_path(team_selection) do %>
              <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            <% end %>
          </td>
          <td>
          <%= link_to team_selection_path(team_selection), method: :delete, data: { confirm: 'Are you sure?'} do %>
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/team_selections/new.html.erb
<h1 class="sub-header">New team selection</h1>

<%= render 'form' %>